
server:
  port: 8080


#spring:
#  security:
#    filter:
#      order: 100

hmac-verify:
  header:
    nonce: nonce
    access-key: accesskey
    authorization: authorization
  server:
    scheme: http
    host: localhost
    port: 8080

  access-key: f9ecb7d7-f5e5-40e1-bc9b-6b5e4ed6cfe0
  secret-key: f9ecb7d7-f5e5-40e1-bc9b-6b5e4ed6cfe0
logging:
  level:
    io:
      github:
        qyvlik:
          springhmacrestverify:
            modules:
              verify:
                interceptor: DEBUG
